# otel config goes here
extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: ":8887"
  prometheusremotewrite:
    endpoint: "http://prometheus.test-opentelemetry-collector-rock-prometheus-integration.svc.cluster.local:9090/api/v1/write"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [debug, prometheus, prometheusremotewrite]
  extensions: [health_check]
  telemetry:
    metrics:
      level: basic # Set to 'normal' or 'detailed' for more metrics
